import fs from 'node:fs/promises'
import path from 'node:path'
import url from 'node:url'

import type { Plugin } from 'vite'

const ROUTES_DIR = path.join('src', 'routes')
const OUTPUT_FILE = path.join('src', 'routeTree.gen.ts')
const ROUTE_FILE_PATTERN = /\.(ts|tsx)$/u

type RouteInfo = {
  fullPath: string
  id: string
  importPath: string
  matchPath: string | null
  parentId: string | null
  sourcePath: string
  to: string
  isPathlessFile: boolean
}

function toPosix(value: string) {
  return value.split(path.sep).join('/')
}

function isPathlessSegment(segment: string) {
  return segment.startsWith('_') && segment !== '__root'
}

async function walkFiles(dirPath: string): Promise<string[]> {
  try {
    const entries = await fs.readdir(dirPath, { withFileTypes: true })
    const nestedFiles = await Promise.all(entries.map(async (entry) => {
      const fullPath = path.join(dirPath, entry.name)

      if (entry.isDirectory()) {
        return walkFiles(fullPath)
      }

      return entry.isFile() ? [fullPath] : []
    }))

    return nestedFiles.flat()
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return []
    }

    throw error
  }
}

function getRouteInfo(filePath: string, routesDir: string): RouteInfo {
  const relativePath = toPosix(path.relative(routesDir, filePath))
  const withoutExtension = relativePath.replace(ROUTE_FILE_PATTERN, '')
  const importPath = `./routes/${withoutExtension}`

  if (withoutExtension === '__root') {
    return {
      fullPath: '/',
      id: '__root__',
      importPath,
      matchPath: null,
      parentId: null,
      sourcePath: withoutExtension,
      to: '/',
      isPathlessFile: false,
    }
  }

  const segments = withoutExtension.split('/')
  const isIndex = segments[segments.length - 1] === 'index'
  const fileSegment = segments[segments.length - 1]
  const directorySegments = segments.slice(0, -1)
  const publicDirectorySegments = directorySegments.filter((segment) => !isPathlessSegment(segment))
  const isPathlessFile = isPathlessSegment(fileSegment)
  const publicSegments = isIndex || isPathlessFile
    ? publicDirectorySegments
    : [...publicDirectorySegments, fileSegment]
  const fullPath = publicSegments.length > 0 ? `/${publicSegments.join('/')}` : '/'
  const id = withoutExtension === 'index'
    ? '/'
    : isIndex
      ? `/${directorySegments.join('/')}/`
      : `/${withoutExtension}`

  return {
    fullPath,
    id,
    importPath,
    matchPath: isPathlessFile ? null : fullPath,
    parentId: '__root__',
    sourcePath: withoutExtension,
    to: fullPath,
    isPathlessFile,
  }
}

function findParentRouteId(route: RouteInfo, routesBySourcePath: Map<string, RouteInfo>) {
  if (route.id === '__root__') {
    return null
  }

  const sourceSegments = route.sourcePath.split('/')
  const directorySegments = sourceSegments.slice(0, -1)

  for (let depth = directorySegments.length; depth > 0; depth -= 1) {
    const candidateSourcePath = directorySegments.slice(0, depth).join('/')
    const candidateRoute = routesBySourcePath.get(candidateSourcePath)

    if (candidateRoute?.isPathlessFile) {
      return candidateRoute.id
    }
  }

  return '__root__'
}

function assertNoDuplicateMatchPaths(routes: RouteInfo[]) {
  const seen = new Map<string, string>()

  routes.forEach((route) => {
    if (!route.matchPath) {
      return
    }

    const existing = seen.get(route.matchPath)

    if (existing) {
      throw new Error(`Duplicate routable path '${route.matchPath}' detected for '${existing}' and '${route.sourcePath}'`)
    }

    seen.set(route.matchPath, route.sourcePath)
  })
}

function createGeneratedFile(routes: RouteInfo[]) {
  const sortedRoutes = [...routes].sort((left, right) => {
    if (left.id === '__root__') return -1
    if (right.id === '__root__') return 1
    return left.id.localeCompare(right.id)
  })

  const routesById = sortedRoutes
    .map((route) => `  '${route.id}': typeof import('${route.importPath}')['Route']`)
    .join('\n')

  const routesByFullPath = sortedRoutes
    .filter((route) => route.id !== '__root__' && route.matchPath !== null)
    .map((route) => `  '${route.fullPath}': typeof import('${route.importPath}')['Route']`)
    .join('\n')

  const routesByTo = sortedRoutes
    .filter((route) => route.id !== '__root__' && route.matchPath !== null)
    .map((route) => `  '${route.to}': typeof import('${route.importPath}')['Route']`)
    .join('\n')

  const manifestEntries = sortedRoutes.map((route) => `  {
    id: '${route.id}',
    fullPath: '${route.fullPath}',
    matchPath: ${route.matchPath ? `'${route.matchPath}'` : 'null'},
    to: '${route.to}',
    parentId: ${route.parentId ? `'${route.parentId}'` : 'null'},
    importPath: '${route.importPath}',
    loadRoute: () => import('${route.importPath}'),
  }`).join(',\n')

  return `/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by VorzelaJs.
// Do not edit this file manually.

import type { GeneratedRouteRecord } from './router/types'

export const routeManifest = [
${manifestEntries}
] as const satisfies readonly GeneratedRouteRecord[]

export interface FileRoutesById {
${routesById}
}

export interface FileRoutesByFullPath {
${routesByFullPath}
}

export interface FileRoutesByTo {
${routesByTo}
}

export type RouteId = keyof FileRoutesById
export type RouteFullPath = keyof FileRoutesByFullPath
export type RouteTo = keyof FileRoutesByTo
`
}

async function writeIfChanged(filePath: string, content: string) {
  const current = await fs.readFile(filePath, 'utf-8').catch(() => null)

  if (current !== content) {
    await fs.writeFile(filePath, content, 'utf-8')
  }
}

export async function generateRoutes(projectRoot = process.cwd()) {
  const routesDir = path.resolve(projectRoot, ROUTES_DIR)
  const outputPath = path.resolve(projectRoot, OUTPUT_FILE)
  const routeFiles = (await walkFiles(routesDir))
    .filter((filePath) => ROUTE_FILE_PATTERN.test(filePath))
    .filter((filePath) => !filePath.endsWith('.d.ts'))

  const routes = routeFiles.map((filePath) => getRouteInfo(filePath, routesDir))

  if (!routes.some((route) => route.id === '__root__')) {
    throw new Error(`Missing root route file at ${path.join(routesDir, '__root.tsx')}`)
  }

  const routesBySourcePath = new Map(routes.map((route) => [route.sourcePath, route] as const))
  const routesWithParents = routes.map((route) => ({
    ...route,
    parentId: findParentRouteId(route, routesBySourcePath),
  }))

  assertNoDuplicateMatchPaths(routesWithParents)

  await writeIfChanged(outputPath, createGeneratedFile(routesWithParents))
}

export function vorzelaRoutesPlugin(): Plugin {
  let projectRoot = process.cwd()

  return {
    name: 'vorzelajs-routes',
    enforce: 'pre',
    configResolved(config) {
      projectRoot = config.root
    },
    async buildStart() {
      await generateRoutes(projectRoot)
    },
    configureServer(server) {
      const routesRoot = path.resolve(projectRoot, ROUTES_DIR)

      const handleRouteChange = async (filePath: string) => {
        const absolutePath = path.resolve(filePath)

        if (!absolutePath.startsWith(routesRoot) || !ROUTE_FILE_PATTERN.test(absolutePath)) {
          return
        }

        try {
          await generateRoutes(projectRoot)
          server.ws.send({ type: 'full-reload' })
        } catch (error) {
          server.config.logger.error(`[vorzelajs-routes] ${(error as Error).message}`)
        }
      }

      server.watcher.on('add', handleRouteChange)
      server.watcher.on('change', handleRouteChange)
      server.watcher.on('unlink', handleRouteChange)
    },
  }
}

const __filename = url.fileURLToPath(import.meta.url)

if (process.argv[1] && path.resolve(process.argv[1]) === __filename) {
  generateRoutes().catch((error) => {
    console.error(error)
    process.exitCode = 1
  })
}