/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by VorzelaJs.
// Do not edit this file manually.

import type { GeneratedRouteRecord } from './router/types'

export const routeManifest = [
  {
    id: '__root__',
    fullPath: '/',
    matchPath: null,
    to: '/',
    parentId: null,
    importPath: './routes/__root',
    loadRoute: () => import('./routes/__root'),
  },
  {
    id: '/',
    fullPath: '/',
    matchPath: '/',
    to: '/',
    parentId: '__root__',
    importPath: './routes/index',
    loadRoute: () => import('./routes/index'),
  },
  {
    id: '/_guest',
    fullPath: '/',
    matchPath: null,
    to: '/',
    parentId: '__root__',
    importPath: './routes/_guest',
    loadRoute: () => import('./routes/_guest'),
  },
  {
    id: '/_guest/login',
    fullPath: '/login',
    matchPath: '/login',
    to: '/login',
    parentId: '/_guest',
    importPath: './routes/_guest/login',
    loadRoute: () => import('./routes/_guest/login'),
  },
  {
    id: '/$',
    fullPath: '/$',
    matchPath: '/$',
    to: '/$',
    parentId: '__root__',
    importPath: './routes/$',
    loadRoute: () => import('./routes/$'),
  },
  {
    id: '/about',
    fullPath: '/about',
    matchPath: '/about',
    to: '/about',
    parentId: '__root__',
    importPath: './routes/about',
    loadRoute: () => import('./routes/about'),
  },
  {
    id: '/errors/loader',
    fullPath: '/errors/loader',
    matchPath: '/errors/loader',
    to: '/errors/loader',
    parentId: '__root__',
    importPath: './routes/errors/loader',
    loadRoute: () => import('./routes/errors/loader'),
  },
  {
    id: '/errors/render',
    fullPath: '/errors/render',
    matchPath: '/errors/render',
    to: '/errors/render',
    parentId: '__root__',
    importPath: './routes/errors/render',
    loadRoute: () => import('./routes/errors/render'),
  },
  {
    id: '/filters',
    fullPath: '/filters',
    matchPath: '/filters',
    to: '/filters',
    parentId: '__root__',
    importPath: './routes/filters',
    loadRoute: () => import('./routes/filters'),
  },
  {
    id: '/posts/',
    fullPath: '/posts',
    matchPath: '/posts',
    to: '/posts',
    parentId: '__root__',
    importPath: './routes/posts/index',
    loadRoute: () => import('./routes/posts/index'),
  },
  {
    id: '/posts/$postId',
    fullPath: '/posts/$postId',
    matchPath: '/posts/$postId',
    to: '/posts/$postId',
    parentId: '__root__',
    importPath: './routes/posts/$postId',
    loadRoute: () => import('./routes/posts/$postId'),
  },
  {
    id: '/server-payload',
    fullPath: '/server-payload',
    matchPath: '/server-payload',
    to: '/server-payload',
    parentId: '__root__',
    importPath: './routes/server-payload',
    loadRoute: () => import('./routes/server-payload'),
  }
] as const satisfies readonly GeneratedRouteRecord[]

export interface FileRoutesById {
  '__root__': typeof import('./routes/__root')['Route']
  '/': typeof import('./routes/index')['Route']
  '/_guest': typeof import('./routes/_guest')['Route']
  '/_guest/login': typeof import('./routes/_guest/login')['Route']
  '/$': typeof import('./routes/$')['Route']
  '/about': typeof import('./routes/about')['Route']
  '/errors/loader': typeof import('./routes/errors/loader')['Route']
  '/errors/render': typeof import('./routes/errors/render')['Route']
  '/filters': typeof import('./routes/filters')['Route']
  '/posts/': typeof import('./routes/posts/index')['Route']
  '/posts/$postId': typeof import('./routes/posts/$postId')['Route']
  '/server-payload': typeof import('./routes/server-payload')['Route']
}

export interface FileRoutesByFullPath {
  '/': typeof import('./routes/index')['Route']
  '/login': typeof import('./routes/_guest/login')['Route']
  '/$': typeof import('./routes/$')['Route']
  '/about': typeof import('./routes/about')['Route']
  '/errors/loader': typeof import('./routes/errors/loader')['Route']
  '/errors/render': typeof import('./routes/errors/render')['Route']
  '/filters': typeof import('./routes/filters')['Route']
  '/posts': typeof import('./routes/posts/index')['Route']
  '/posts/$postId': typeof import('./routes/posts/$postId')['Route']
  '/server-payload': typeof import('./routes/server-payload')['Route']
}

export interface FileRoutesByTo {
  '/': typeof import('./routes/index')['Route']
  '/login': typeof import('./routes/_guest/login')['Route']
  '/$': typeof import('./routes/$')['Route']
  '/about': typeof import('./routes/about')['Route']
  '/errors/loader': typeof import('./routes/errors/loader')['Route']
  '/errors/render': typeof import('./routes/errors/render')['Route']
  '/filters': typeof import('./routes/filters')['Route']
  '/posts': typeof import('./routes/posts/index')['Route']
  '/posts/$postId': typeof import('./routes/posts/$postId')['Route']
  '/server-payload': typeof import('./routes/server-payload')['Route']
}

export type RouteId = keyof FileRoutesById
export type RouteFullPath = keyof FileRoutesByFullPath
export type RouteTo = keyof FileRoutesByTo
