/* eslint-disable */

// This file was automatically generated by VorzelaJs.
// Do not edit this file manually.

import type { GeneratedRouteHydrationRecord } from './router/types.js'

export const routeHydrationManifest = {
  '__root__': { detected: 'static' },
  '/': { detected: 'client' },
  '/_guest': { detected: 'static' },
  '/_guest/login': { detected: 'static' },
  '/$': { detected: 'static' },
  '/about': { detected: 'static' },
  '/errors/loader': { detected: 'client' },
  '/errors/render': { detected: 'static' },
  '/filters': { detected: 'client' },
  '/posts/': { detected: 'static' },
  '/posts/$postId': { detected: 'static' },
  '/server-payload': { detected: 'static' }
} as const satisfies Readonly<Record<string, GeneratedRouteHydrationRecord>>
